services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123
    ports:
      - 27017:27017


  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend 
    restart: on-failure
    environment:
      - MONGO_URL=mongodb://admin:123@mongodb:27017
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBIT_MQ_QUEUE=logsQueue
    depends_on:
      rabbitmq:
        condition: service_healthy

    ports:
      - 3000:3000

